### ISSUE TITLE
Wordpress: Online contribution page does not work

### ISSUE THREAD

**Issue by mattwire** [mattwire/com.drastikbydesign.stripe#11]
No visible error message. Stripe default/Stripe alternate both enabled.  Confirm payment goes back to the initial contribution page and payment is not submitted.

**Comment by cyberhiker** [comment]
@mattwire Were you going to work on this issue.  Just wondering, I'm having the same problem and if you were already going to do it, then I was going to wait.

**Comment by mattwire** [comment]
@cyberhiker It is likely to be a simple fix - we've been tweaking civicrm_stripe.js again to improve consistency/remove bugs with jquery versions etc.  However, that appears to have broken wordpress support again.  As I don't currently have any clients/funding to look into/fix it there I've raised it as an issue for now.  So if you are able to look into it that would be really helpful!  Lot's of debug is output to the browser console which should help identify where it is going wrong.

**Comment by cyberhiker** [comment]
So I've been fighting with this on my own for a few days now.  Can you give me an estimate as to what it might cost to get it fixed?

**Comment by mattwire** [comment]
@cyberhiker Can you test the https://github.com/mattwire/com.drastikbydesign.stripe/tree/wordpress_dev branch and let me know if that fixes the issue for you?

**Comment by mattwire** [comment]
@cyberhiker Please test 5.x-dev branch and let me know if it is working now?

**Comment by cyberhiker** [comment]
I will definitely check it this weekend.  I have to upgrade CiviCRM.

-C

~~~~~~~~
Chris Burton, CISSP
443.486.0111 (Office)
240.793.9123 (Mobile)
On Aug 1, 2018, 11:35 AM -0400, Matthew Wire <notifications@github.com>, wrote:
> @cyberhiker Please test 5.x-dev branch and let me know if it is working now?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mattwire** [comment]
Fixed in https://github.com/mattwire/com.drastikbydesign.stripe/releases/tag/5.0.beta4

**Comment by cyberhiker** [comment]
Yes.  It is working.
