### ISSUE TITLE
Support Charging Cards in the admin end

### ISSUE THREAD

**Issue by yosefromano** [mattwire/com.drastikbydesign.stripe#15]
I just read through the previous issue. 
We would greatly benefit from a feature that allows Civi Admins to charge a contact's card in the admin end without haveing to enter the CC#. Something that I think well benefit most people.
Certainly, we can connect the Civi Contact with the stripe customer and put a button Record Contribution page to charge the card.

![screen shot 2018-06-17 at 11 18 23 am](https://user-images.githubusercontent.com/10218159/41510847-6f4af8b2-7220-11e8-9831-ee10dd1ec4e2.png)

**Comment by mattwire** [comment]
Ref #14

**Comment by mattwire** [comment]
Extension now at https://lab.civicrm.org/extensions/stripe
