### ISSUE TITLE
Masking of values before form submission is breaking webforms

### ISSUE THREAD

**Issue by petednz** [mattwire/com.drastikbydesign.stripe#17]
Just getting this lodged here for now. 

tested after upgrading to beta-3 (was failing us on beta-1 hence trying the latest)

issue is when using a webform - after entering the CC values - upon Submit the values get masked and the webform returns "Please enter a valid Card Number"

**Comment by petednz** [comment]
Found we had some scripts running on this form - so i retried on a vanilla form 

I still see "It looks like Stripe.js was loaded more than one time"

And I still get "Please enter a valid Card Number" with the  cc values showing as 0000000000005213

**Comment by mattwire** [comment]
@petednz I think you fixed this? By updating webform_civicrm?

**Comment by petednz** [comment]
yes though perhaps it involved pr 100 too? may be confusing issues. travelling. jetlagged. closing ;-)
