### ISSUE TITLE
Could not cancel subscription

### ISSUE THREAD

**Issue by madhavimalgaonkar** [mattwire/com.drastikbydesign.stripe#19]
###Testing Stripe payment processor using this fork on Drupal 7.59 and Civicrm 5.3.2.

- [x] I have configured the processor using test credentials. 

- [X] Created one contribution page and made one recurring contribution which is created as `CiviCRM every 1 day(s) 100.00usd` on stripe dashboard.

- [X] Configured and tested webhook.

When I cancel the subscription from stripe dashboard it does not reflect on my civicrm dashboard. The recurring contribution still says `Pending`.
And in the response of webhook it returned `CiviCRM_API3_Exception: "Expected one Contribution but found 0"`

**Comment by mattwire** [comment]
Thankyou for the report.  We would like to get this working.

@madhavimalgaonkar If you can create a PR I will review and we can get it fixed?

I think it must be failing here: https://github.com/mattwire/com.drastikbydesign.stripe/blob/5.x/CRM/Core/Payment/StripeIPN.php#L543

**Comment by madhavimalgaonkar** [comment]
Thanks :) I was working in test mode so just had to comment this line and test. Worked fine. https://github.com/mattwire/com.drastikbydesign.stripe/blob/5dc10a2dea3ed159135a6744084b74e81fc4f778/CRM/Core/Payment/StripeIPN.php#L547

Found new issue though. 
- I have created one recurring contribution on 29th August. And it was 1 installment for 1 day plan.
- Which means I was subscribed to `every-1-day-12000-usd` plan. 
- And as per civiCRM as it is 1 installment my recurring contribution should end on `30st August`. 
- But I still got billed on 31st August. Now in the upcoming invoiced it says next payment will be billed on 1st September. And the recurring contribution status says `In Progress`.

Ideally it should have stopped and changed the status to completed right? It wont be user friendly if everytime user need to cancel the subscription manually from stripe dashboard.

**Comment by sushantpaste** [comment]
Hey guys Any updates on this issue?

**Comment by mattwire** [comment]
@sushantpaste Just needs someone to fund some work on it :-)

**Comment by madhavimalgaonkar** [comment]
Hey guys, I have 2 approaches to achieve this.
1. We can create a scheduled job which will run when cron runs. This job will cancel the recurring contribution at the `end_time` specified. The end time is saved in `civicrm_stripe_subscriptions` table which is the calculation of No. of instalments.

2. We have a webhook which listen to events happened in stripe dashboard. In the webhook will check the number of invoices paid in stripe matches the instalments specified in recurring contribution. When the number matches then will cancel the subscription.

Suggest which one is more robust and right way to handle the automatic cancellation scenario.

**Comment by mattwire** [comment]
@madhavimalgaonkar Please take a look at https://github.com/drastik/com.drastikbydesign.stripe/pull/241 for how this should be solved.  If you can create a PR here based on that one then I can review.

**Comment by mattwire** [comment]
Extension now at https://lab.civicrm.org/extensions/stripe
