### ISSUE TITLE
Processing Contribution in Admin Blanks Out Email Address

### ISSUE THREAD

**Issue by mwoodward-atd** [mattwire/com.drastikbydesign.stripe#21]
Environment:
* WordPress 4.9.8
* CiviCRM 5.4.0
* Stripe extension 5.0 beta 4

Process to reproduce:
1. Contributions -> New Contribution
2. Click "submit credit card contribution" link on right
3. Select a contact that you know for sure has an email address
4. Fill out the rest of the form
5. Click Save
6. Results in error message "No email address found. Please report this issue." (screenshot attached)
7. Go to contact record, see that email address is now blank

![stripe-extension-error](https://user-images.githubusercontent.com/16122396/44962231-011f6500-aed2-11e8-9e4c-8d35461df551.png)

Note that if you go directly to the contact record, go to the contact's contributions tab, and click the "Submit Credit Card Contribution" button, that works fine and does not blank out the email address.

Let me know if you need more details. Thanks.

**Comment by highfalutin** [comment]
Not only is the email address "not found", it is deleted from the contact record!

**Comment by mattwire** [comment]
This is not actually a Stripe issue but a CiviCRM core issue that affects any payment processed using the steps above.  See https://github.com/civicrm/civicrm-core/pull/12839

**Comment by mwoodward-atd** [comment]
Thanks for following that up on the core!
