### ISSUE TITLE
Are you sure you want to leave this page?

### ISSUE THREAD

**Issue by adam-devapp** [mattwire/com.drastikbydesign.stripe#23]
![payment_methods](https://user-images.githubusercontent.com/13082954/45790962-a144fe80-bcc6-11e8-8a83-93c4dddd5da3.png)
![error](https://user-images.githubusercontent.com/13082954/45790963-a144fe80-bcc6-11e8-8854-ee53a363b6aa.png)

When using this fork of the module with CiviCRM 5.5.1 and Drupal 7, the message Are you sure you want to leave is displayed when selecting offline payment.

**Comment by mattwire** [comment]
Hi, so I think that is your web browser detecting a form on the page and offering you a chance to not lose the data on it.  I'm not sure if there is any way for the page to tell the browser not to show that?

**Comment by mattwire** [comment]
Resolved in 5.2 https://lab.civicrm.org/extensions/stripe/tags/5.2
