### ISSUE TITLE
Strong Customer Authentication (SCA) PSD2 requirements

### ISSUE THREAD

**Issue by bradydan** [mattwire/com.drastikbydesign.stripe#24]
Is this extension compatible with the new Strong Customer Authentication (SCA) PSD2 requirements?

https://stripe.com/gb/payments/strong-customer-authentication

**Comment by mattwire** [comment]
@bradydan This extension now lives here: https://lab.civicrm.org/extensions/stripe

We have a version using stripe elements and paymentIntents due for beta release any day now.
